//
//  PPlaceListViewController.swift
//  PuntersWeather
//
//  Created by Noble Mathew on 26/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreData

protocol PPlaceListViewControllerInput {
  func loadData()
}

protocol PPlaceListViewControllerOutput {
  func getWeatherData()
}

class PPlaceListViewController: UIViewController, PPlaceListViewControllerInput {
  //MARK: - VC Elements
  var output: PPlaceListViewControllerOutput!
  var router: PPlaceListRouter!
  
  lazy var menuView: MenuView = {
    let menu = MenuView()
    menu.homeController = self
    return menu
  }()
  
  @IBOutlet weak var listCollectionView: UICollectionView!
  @IBOutlet weak var searchBar: UISearchBar!
  @IBOutlet weak var filterBarButton: UIBarButtonItem!
  
  let cellIdentifier = "WeatherCell"
  let headerIdentifier = "PPlaceHeaderCell"
  var weatherItems = [Weather]()
  var filteredItems = [Weather]()
  var isFiltered = false
  let managedContext = CoreDataStack.shared.persistentContainer.viewContext
  var countryList = [String]()
  var weatherList = [String]()
  
  // MARK: - Object lifecycle
  override func awakeFromNib() {
    super.awakeFromNib()
  }
  
  // MARK: - View lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
    PPlaceListConfigurator.sharedInstance.configure(viewController: self)
    
    self.title = "WW"
    self.navigationController?.regularNavigationBar()
    self.automaticallyAdjustsScrollViewInsets = false
    
    //Get weather Deatils
    WeatherActivityIndicator.showActivityIndicator(self.view)
    output.getWeatherData()
  }
  
  override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    
    self.searchBar.resignFirstResponder()
  }
  
  override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    menuView.handleBackgroundViewDismiss()
  }
  
  // MARK: - Event handling
  /**
   Load the data from the core data stack
   */
  func loadData() {
    let weatherDataUpdate: NSFetchRequest<Weather> = Weather.fetchRequest()
    do {
      weatherItems = try managedContext.fetch(weatherDataUpdate)
      weatherItems = weatherItems.sorted {
        $0.0.placeName! < $0.1.placeName!
      }
      countryList = weatherItems.flatMap {
        $0.countryDetails?.countryName
      }.unique()
      weatherList = weatherItems.flatMap {
        $0.weatherCondition
      }.unique()
      DispatchQueue.main.async {
        WeatherActivityIndicator.hideActivityIndicator(self.view)
        self.listCollectionView.reloadData()
      }
    } catch {
      print("Error fetching data \(error.localizedDescription)")
    }
  }
  
  //MARK: - IB Actions
  @IBAction func filterResults(_ sender: Any) {
    menuView.showSettings(.filter)
  }
  
  @IBAction func refreshList(_ sender: Any) {
    weatherItems = []
    WeatherActivityIndicator.showActivityIndicator(self.view)
    output.getWeatherData()
    listCollectionView.setNeedsDisplay()
  }
  
  @IBAction func sortList(_ sender: Any) {
    //Show sort menu to figure out way to sort
    menuView.showSettings(.sort)
  }
  
  //MARK: - Sorting Method
  /**
   Method used to change the sorting of the dataSource
   
   - parameter sortType: Sort type enum used to determine the base for sorting the database
 */
  func sortListUsing(_ sortType: SortingTypes) {
    switch sortType {
    case .alphabetically:
      if isFiltered {
        filteredItems = filteredItems.sorted {
          $0.placeName!.localizedCaseInsensitiveCompare($1.placeName!) == ComparisonResult.orderedAscending
        }
      } else {
        weatherItems = weatherItems.sorted {
          $0.placeName!.localizedCaseInsensitiveCompare($1.placeName!) == ComparisonResult.orderedAscending
        }
      }
      break
    case .temperature:
      if isFiltered {
        filteredItems = filteredItems.sorted {
          $0.weatherTemperature < $1.weatherTemperature
        }
      } else {
        weatherItems = weatherItems.sorted {
          $0.weatherTemperature < $1.weatherTemperature
        }
      }
      break
    case .lastUpdated:
      if isFiltered {
        filteredItems = filteredItems.sorted {
          $0.weatherLastUpdated < $1.weatherLastUpdated
        }
      } else {
        weatherItems = weatherItems.sorted {
          $0.weatherLastUpdated < $1.weatherLastUpdated
        }
      }
      break
    default:
      break
    }
    self.listCollectionView.reloadData()
  }
  
  //MARK: - Filtering Method
  /**
   Filter the datasoure using the filter value provided
   
   - parameter filterType: Filter type enum that is used to figure out the parameter that needs to be used to be filtered
   - parameter filterValue: Filter value used to fetch the appropriater resuts
 */
  func filerListUsing(_ filterType: FilterIngType, filterValue: String) {
    switch filterType {
    case .country:
      filteredItems = weatherItems.filter {
        $0.countryDetails?.countryName == filterValue
      }
      isFiltered = true
      filterBarButton.tintColor = .black
      break
    case .weatherCondition:
      filteredItems = weatherItems.filter {
        $0.weatherCondition == filterValue
      }
      isFiltered = true
      filterBarButton.tintColor = .black
      break
    case .removeFilter:
      isFiltered = false
      filterBarButton.tintColor = .white
      break
    default:
      break
    }
    self.listCollectionView.reloadData()
  }
}


//MARK: - CollectionView Delegate
extension PPlaceListViewController: UICollectionViewDelegate {
  
  /**
   The Delegate method to tell the collectionView, what to do when a colectionView
   cell is tapped.
   */
  func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    
  }
  
  func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
    cell.alpha = 0
    
    UIView.animate(withDuration: 1.0) {
      cell.alpha = 1
    }
  }
  
}

//MARK: - CollectionView DataSource
extension PPlaceListViewController: UICollectionViewDataSource {
  
  /**
   Delegate method to set the number of rows per collection
   */
  func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
    print("count \(weatherItems.count)")
    if isFiltered {
      return filteredItems.count
    }
    return weatherItems.count
  }
  
  /**
   optional Delegate method to set the number of sections
   */
  func numberOfSections(in collectionView: UICollectionView) -> Int {
    return 1
  }
  
  /**
   CollectionView DataSource method to set the cell for each item
   */
  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: cellIdentifier, for: indexPath) as! PPlaceListCollectionViewCell
    
    var weatherData: Weather!
    if isFiltered {
      weatherData = filteredItems[indexPath.item]
    } else {
      weatherData = weatherItems[indexPath.item]
    }
    
    cell.placeNameLabel.text = weatherData.placeName
    cell.temperatureLabel.text = "\(weatherData.weatherTemperature) ºc"
    cell.lastUpdateLabel.text = "Last updated on \(weatherData.weatherLastUpdated.convertToDateString())"
    cell.weatherConditionLabel.text = weatherData.countryDetails?.countryName
    
    return cell
  }
  
  func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
    var reuseableView = UICollectionReusableView()
    if kind == UICollectionElementKindSectionHeader {
      let headerCell = collectionView.dequeueReusableSupplementaryView(ofKind: UICollectionElementKindSectionHeader, withReuseIdentifier: headerIdentifier, for: indexPath) as! PPlacelistheaderCollectionReusableView
      headerCell.lastUpdatedLabel.text = "Last updated at \(Date().toReadableString())"
      reuseableView = headerCell
    }
    return reuseableView
  }
}

//MARK: - SearchBar Delegate
extension PPlaceListViewController: UISearchBarDelegate {
  
  func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
    filteredItems = weatherItems.filter {
      $0.placeName!.contains(searchText)
    }
    isFiltered = true
    self.listCollectionView.reloadData()
    
    if searchText.isEmpty {
      isFiltered = false
      self.listCollectionView.reloadData()
      searchBar.resignFirstResponder()
    }
  }
  
  func searchBarTextDidEndEditing(_ searchBar: UISearchBar) {
    searchBar.resignFirstResponder()
  }
  
}

//MARK: - Scroll View Delegate
extension PPlaceListViewController: UIScrollViewDelegate {
  
  func scrollViewDidScroll(_ scrollView: UIScrollView) {
    self.searchBar.resignFirstResponder()
  }
}
