//
//  PPlaceListConfigurator.swift
//  PuntersWeather
//
//  Created by Noble Mathew on 26/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PPlaceListViewController: PPlaceListPresenterOutput {
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    router.passDataToNextScene(segue: segue)
  }
}

extension PPlaceListInteractor: PPlaceListViewControllerOutput {
}

extension PPlaceListPresenter: PPlaceListInteractorOutput {
}

class PPlaceListConfigurator {
  // MARK: - Object lifecycle
  
  static let sharedInstance = PPlaceListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: PPlaceListViewController) {
    let router = PPlaceListRouter()
    router.viewController = viewController
    
    let presenter = PPlaceListPresenter()
    presenter.output = viewController
    
    let interactor = PPlaceListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
